name: Full Service Build

env:
  # DOCKERHUB_REPO: mobilecoin/full-service
  DOCKERHUB_REPO: mcrank/full-service

on:
  push:
    tags:
      - 'v*'
    branches:
      - 'mcrank-ci'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - namespace: test
            network: testnet
          - namespace: prod
            network: mainnet
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Generate Docker tags
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.DOCKERHUB_REPO }}
          flavor: |
            latest=false
            suffix=${{ matrix.network }}
            type=semver,pattern=v{{version}},priority=20
          tags: |
            type=sha,priority=10

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Publish to DockerHub
        id: docker_publish_dockerhub
        uses: docker/build-push-action@v2
        with:
          build-args: |
            NAMESPACE=${{ matrix.namespace }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
